# Numpy AKA numetic python.

## Arrays in Numpy

In [1]:
import numpy as np

In [9]:
arr = np.array([1,2,3])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
1


In [3]:
mat = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(mat)
print(mat.ndim)
print(mat.shape)

[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]
2
(3, 3)


In [4]:
# how to access valus in array
print(mat[0][0]) # genric chain indexing 
print(mat[0,0]) #numpy allows ndaimentional indexing 

a
a


## Slicing in Numpy

In [8]:
array = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

# : is the slice operator

print(array[0:3]) # will give from 0 to 2 end is exlusive
print("----------")
print(array[0:2, 1:3]) # [start:end:step]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------
[[2 3]
 [6 7]]


## Scalar Arthmeric

In [ ]:
print(arr + 1)
print(arr - 2)
print(arr * 3)
print(arr ** 2)
print(arr / 2)
# we can perform simple math to each element by this

[2 3 4]
[-1  0  1]
[3 6 9]
[1 4 9]
[0.5 1.  1.5]


## Vector Math Function

In [ ]:
print(np.sqrt(arr))
print(np.round(arr*1.6)) # can go ceil and floor as well
print(np.pi) # used as a costant


[1.         1.41421356 1.73205081]
[2. 3. 5.]
3.141592653589793


In [ ]:
# Excerise 
# area of a circle
# pi * r * r assume radii as array
print(np.pi * arr ** 2)


[ 3.14159265 12.56637061 28.27433388]


## Element wise arthmetic

In [18]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 + array2)
print(array1 - array2)
print(array1 / array2)
print(array1 * array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]
[  1  32 729]


## Comparision Operator

In [20]:
scores = np.array([32,99,75,100])

print(scores == 100) ## will return a boolean array true if arr[i] == 100
# same can be done with any type of operator

[False False False  True]


## broadCasting

In [22]:
# broadcasting in numpy means we can do maths in 
# - same size of array for each attribute
# - one of the array should be of size 1 

arr1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
arr2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(arr1.shape) # 1, 10
print(arr2.shape) # 10, 1
# either one is 1 or things should be same
print(arr1 * arr2)



(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


# Aggregate Function

In [26]:
# aggregate functions summersize data and return a single value
# array = np.array([
#     [1,2,3,4],
#     [5,6,7,8],
#     [9,10,11,12]
# ])

print("sum : " , np.sum(array))
print("min : " , np.min(array))
print("max : " , np.max(array))
print("minIdx : " , np.argmin(array)) # index of max
print("maxIdx : " , np.argmax(array)) # index of min
print("mean : " , np.mean(array))
print("median : " , np.median(array))
print("standard Diviation : " , np.std(array)) # standard Diviation
print("varince : " , np.var(array)) # varince


sum :  78
min :  1
max :  12
minIdx :  0
maxIdx :  11
mean :  6.5
median :  6.5
standard Diviation :  3.452052529534663
varince :  11.916666666666666


## Filtering

In [34]:
# process of selecting elements which matches a given condition
ages = np.array([
    [45,19,16,18,20,34,56],
    [8,14,7,25,22,23,28]
])

can_vote = ages[ages >= 18]
kids = ages[ages < 18]
even = ages[ages % 2 == 0]
print(can_vote)
print(kids)
print(even)
print("--------------")
# where clause
above_18 = np.where(ages >= 18, ages, 0)
print(above_18)

[45 19 18 20 34 56 25 22 23 28]
[16  8 14  7]
[16 18 20 34 56  8 14 22 28]
--------------
[[45 19  0 18 20 34 56]
 [ 0  0  0 25 22 23 28]]


## Randoms

In [40]:
rng = np.random.default_rng() # random generation

print(rng.integers(0,101)) # between 0 to 100 end value is exclusive
print("---------")
print(rng.integers(low = 0, high = 101, size = (3,2))) #we can genrate arrays as well
print("---------")

# shuffle
print(arr)
rng.shuffle(arr)
print(arr)
print("---------")

# choice
num = rng.choice(arr)
print(num)

74
---------
[[42 34]
 [79 81]
 [77 24]]
---------
[3 2 1]
[1 2 3]
---------
2
